import { copyFile, mkdir, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { build } from "esbuild";


const projectDir = dirname(fileURLToPath(import.meta.url));
const outputDir = join(projectDir, "dist");
const bundlePath = join(projectDir, "app.bundle.js");

await build({
  absWorkingDir: projectDir,
  entryPoints: ["app.js"],
  outfile: bundlePath,
  bundle: true,
  format: "esm",
  platform: "browser",
  target: ["es2022"],
  define: {
    "process.env.NODE_ENV": JSON.stringify("production"),
  },
  legalComments: "none",
  alias: {
    "genlayer-js": "./vendor/genlayer-js/index.js",
  },
  banner: {
    js: "/* Generated by npm run build. Edit app.js, not this file. */",
  },
});

const configuration = {
  RPC_URL: (process.env.GENLAYER_RPC_URL || "https://studio.genlayer.com/api").trim(),
  LIVING_CONTRACT_ADDRESS: (
    process.env.LIVING_CONSTITUTION_CONTRACT_ADDRESS ||
    "0x7e397Abe9df988b05266d613b1c099a1458f0Fda"
  ).trim(),
  TRUTH_CONTRACT_ADDRESS: (
    process.env.TRUTHFEED_CONTRACT_ADDRESS ||
    "0x704687cD890E636696F9362708c8832fbcC40773"
  ).trim(),
  REGISTRY_API_BASE: (
    process.env.DECISION_REGISTRY_URL ||
    "https://livingconstitution-nine.vercel.app"
  ).trim().replace(/\/$/, ""),
};

if (process.env.VERCEL === "1") {
  if (!/^https:\/\//.test(configuration.RPC_URL)) {
    throw new Error("GENLAYER_RPC_URL must be an HTTPS URL in Vercel");
  }
  for (const [name, value] of [
    ["LIVING_CONSTITUTION_CONTRACT_ADDRESS", configuration.LIVING_CONTRACT_ADDRESS],
    ["TRUTHFEED_CONTRACT_ADDRESS", configuration.TRUTH_CONTRACT_ADDRESS],
  ]) {
    if (!/^0x[0-9a-fA-F]{40}$/.test(value)) {
      throw new Error(`${name} must be a valid address in Vercel`);
    }
  }
  if (!/^https:\/\//.test(configuration.REGISTRY_API_BASE)) {
    throw new Error("DECISION_REGISTRY_URL must be an HTTPS URL in Vercel");
  }
}

await rm(outputDir, { recursive: true, force: true });
await mkdir(outputDir, { recursive: true });
for (const filename of ["index.html", "how-it-works.html", "styles.css"]) {
  await copyFile(join(projectDir, filename), join(outputDir, filename));
}
await copyFile(bundlePath, join(outputDir, "app.bundle.js"));
await writeFile(
  join(outputDir, "config.js"),
  `window.OracleConfig = ${JSON.stringify(configuration)};\n`,
  "utf8",
);
