import { copyFile, mkdir, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { build } from "esbuild";


const projectDir = dirname(fileURLToPath(import.meta.url));
const outputDir = join(projectDir, "dist");
const bundlePath = join(projectDir, "app.bundle.js");

await build({
  absWorkingDir: projectDir,
  entryPoints: ["app.js"],
  outfile: bundlePath,
  bundle: true,
  format: "esm",
  platform: "browser",
  target: ["es2022"],
  legalComments: "none",
  alias: {
    "genlayer-js": "./vendor/genlayer-js/index.js",
  },
  banner: {
    js: "/* Generated by npm run build. Edit app.js, not this file. */",
  },
});

const rpcUrl = (process.env.GENLAYER_RPC_URL || "https://studio.genlayer.com/api").trim();
const contractAddress = (
  process.env.GENLAYER_CONTRACT_ADDRESS ||
  "0xcf2C42546E652A84aE5A5586707F053B6e299e7a"
).trim();
const registryApiBase = (
  process.env.DECISION_REGISTRY_URL ||
  "https://livingconstitution-nine.vercel.app"
).trim();
if (process.env.VERCEL === "1") {
  if (!/^https:\/\//.test(rpcUrl)) {
    throw new Error("GENLAYER_RPC_URL must be an HTTPS URL in Vercel");
  }
  if (!/^0x[0-9a-fA-F]{40}$/.test(contractAddress)) {
    throw new Error("GENLAYER_CONTRACT_ADDRESS must be a valid address in Vercel");
  }
}

await rm(outputDir, { recursive: true, force: true });
await mkdir(outputDir, { recursive: true });
for (const filename of [
  "index.html",
  "how-it-works.html",
  "how-it-works.js",
  "styles.css",
]) {
  await copyFile(join(projectDir, filename), join(outputDir, filename));
}
await copyFile(bundlePath, join(outputDir, "app.bundle.js"));
await writeFile(
  join(outputDir, "config.js"),
  `window.TruthFeedConfig = ${JSON.stringify({
    RPC_URL: rpcUrl,
    CONTRACT_ADDRESS: contractAddress,
    REGISTRY_API_BASE: registryApiBase,
  })};\n`,
  "utf8",
);
